spec:
  template:
    spec:
      nodeSelector:
        run-ingress-nginx: true
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Equal
          effect: NoSchedule
      externalIPs:
        - 192.168.31.154
        - 192.168.31.248
        - 192.168.31.94
        - 192.168.31.247
