version: "3.9"
services:

  jenkins-custom:
    image: sasha192bunin/jenkins-maven
    privileged: true
    user: root
    volumes:
      - /home/${USER}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-custom
    ports:
      - "8001:8080"
      - "50000:50000"
    profiles:
      - jenkins-custom
