version: "3.9"
services:

  jenkins-custom:
    image: sasha192bunin/jenkins-jdk15
    privileged: true
    user: root
    volumes:
      - /home/${USER}/bitnami/jenkins:/bitnami/jenkins
#      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-custom
    ports:
      - "8001:8080"
      - "50000:50000"
    environment:
      - JENKINS_USERNAME=jenkins
      - JENKINS_PASSWORD=jenkins
    profiles:
      - jenkins-custom
